# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'GoneVisibleExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoneVisibleExample
  pod 'GoneVisible'

  target 'GoneVisibleExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoneVisibleExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
